### ISSUE TITLE
#rebalance_ranks assumes that a record exists

### ISSUE THREAD

**Issue by mkalygin** [mixonic/ranked-model#133] opened 2018-11-20 00:25 UTC
Since there is no new release of this package, I've decided to use `master` branch instead of my own fork. I've recently fixed #90 and it was merged, so why not.

Apparently recent commit 780dbf5b7e31d4cddef3795acf0ee7e26a80be25 causes another bug, because it assumes that a record exists. In fact it may be a new record and it may not have ID yet.

Because of that it throws an error `NoMethodError: undefined method '<' for nil:NilClass` here:
https://github.com/mixonic/ranked-model/blob/master/lib/ranked-model/ranker.rb#L211

Going back to my fork for now. 😄

**Comment by brendon** [comment] 2018-11-20 00:34
Hi @mkalygin, the `destination` comes from `current_order` which is a query on the database so this should be all persisted records. Are you able to come up with a test that fails for this? Then we can work on a fix. It could be a race condition?

**Comment by brendon** [comment] 2018-11-20 00:34
And I'd love to do a gem release, just waiting on @mixonic to give me gem publishing rights :)

**Comment by mkalygin** [comment] 2018-11-20 01:05
@brendon my app's usage example is quite complex. I'll try to repro it in isolated test. But to give you a clue, here is my scenario.

I'm building a new record, which has many items. I also build the items. The default order of them is set in the association declaration. Here is the relevant code:

```
accepts_nested_attributes_for :items
has_many :items, -> { rank(:order) }
```

And when I save the record, I get this error when it's trying to save one of the associated items.

**Comment by brendon** [comment] 2018-11-20 01:09
Thanks @mkalygin, the first place I'd look is `current_order` to see whether the memorisation there is causing problems :)

**Comment by brendon** [comment] 2018-12-10 21:47
@mkalygin, were you able to come up with a failing test case?

**Comment by brendon** [comment] 2018-12-10 21:48
@geoffharcourt, if you're experiencing this too, could you look at creating a test case that fails?

**Comment by geoffharcourt** [comment] 2018-12-11 01:56
I'm having a bit of trouble getting the test case due to the amount of setup required, but the scenario that's failing for us is very straightforward and appears to happen when creating the first record with an ordering attribute at creation time. Our `row_order` attribute on the  model in our application has a `presence: true` validation check, so we always have it specified when we create one.

The specs for `Duck` that I looked at create several models without setting `row_position`, and then bypass callbacks by setting them after creation through `#update_attribute`. I think a simple test case like this:

```ruby
RSpec.describe DuckModel do
  describe "callbacks" do
    it "allows creation with a defined order parameter" do
      expect { Duck.create!(row_order: 1) }.not_to raise_error
    end
  end
end
```

might be all we need to show the failing case.

Here are some examples: https://github.com/mixonic/ranked-model/blob/6f4a76cfef5ecb77bc0a3818d73db5b698e2b369/spec/duck-model/duck_spec.rb#L26-L50.

**Comment by brendon** [comment] 2018-12-11 02:33
Hi @geoffharcourt, thanks for looking into this. I got tricked by this when I first started using `ranked-model`: it's generally not a good idea to set the raw column value from the app end. Instead you need to manipulate the `row_order_position` pseudo-column. The whole point of `ranked-model` is to abstract away the mechanics of the ranking, allowing you to then position items relative to other items (or to named parts of the list (`:first`, `:last` etc...).

Have you tried approaching things from that angle?

The ranking is assigned in a `before_save`: https://github.com/mixonic/ranked-model/blob/master/lib/ranked-model.rb#L18 so everything should be valid upon save. Perhaps we could move this to `before_validation`?

**Comment by geoffharcourt** [comment] 2018-12-11 02:55
`before_validation` would probably help for cases where the ordering term is a required field. The position we're in now is that this field has a presence validation, so we have lots of tests across models that fail because new models will have a `_position` but not the ordering term. 

Given the history of when #96 came into the codebase this strikes me as a breaking API change, and not a patch-version bump.

**Comment by pwim** [comment] 2018-12-11 08:03
There's also an issue in my application's specs related to this (also getting `undefined method '<' for nil:NilClass`). In my app's spec, it occurs when I'm duping a ranked model instance. My ranked model is using the `with_same` option, and I think it might be related to that.

I've hacked a spec to get it to reproduce the issue: https://github.com/pwim/ranked-model/commit/f74e28483e94d8626af30869e377b63dd8dd4b92

It does appear to be ordering dependent, so I'm not sure if others will also see an error when running it. I haven't dug any deeper into what the issue might be.

**Comment by brendon** [comment] 2018-12-11 20:04
Hi @geoffharcourt, #96 (or #132) was just a documentation update. The whole concept of the pseudo-column has been around the whole time as far as I'm aware (at least as long as I've been using the gem).

Thanks @pwim for the update. If either of you have time, would you be able to fork and try to see what happens if we use `before_validation` instead (RE the tests)?

**Comment by brendon** [comment] 2019-03-18 21:22
Hi everyone, this should all be fixed now in a couple of ways. We check for `persisted?` now, and are also checking for `column_defaults` to ensure none is set on the rank column. I'm closing this for now but will reopen it in the case where it's still an issue.

**Closed by brendon** 2019-03-18 21:22 UTC
